'use strict';

/**
 * Encryption configuration and mode selection.
 *
 * Two modes:
 *  - 'local'    : AES-256-GCM using ENCRYPTION_KEY directly (development only).
 *  - 'kms'      : AWS KMS envelope encryption (production). A per-record data key (DEK) is
 *                 generated by KMS, used to encrypt the field with AES-256-GCM, and the
 *                 wrapped DEK is stored alongside the ciphertext.
 *
 * The actual crypto lives in services/encryption/encryption.service.js; this module just
 * resolves configuration and normalises the key material.
 */

const config = require('./index');

function resolveKeyBuffer() {
  const raw = config.encryption.key || '';
  // Accept hex (64 chars), base64, or raw 32-byte utf8.
  if (/^[0-9a-fA-F]{64}$/.test(raw)) return Buffer.from(raw, 'hex');
  const b64 = Buffer.from(raw, 'base64');
  if (b64.length === 32) return b64;
  const utf8 = Buffer.from(raw, 'utf8');
  if (utf8.length === 32) return utf8;
  // Derive a stable 32-byte key from whatever was provided (dev fallback only).
  return require('crypto').createHash('sha256').update(raw).digest();
}

module.exports = {
  mode: config.isProd && config.aws.kmsKeyId ? 'kms' : 'local',
  algorithm: 'aes-256-gcm',
  kmsKeyId: config.aws.kmsKeyId,
  kmsMedicalKeyId: config.aws.kmsMedicalKeyId || config.aws.kmsKeyId,
  resolveKeyBuffer,
};
